version: '3.5'

services: 
    web-service:
        image: rahulraju/simple-php-app:latest
        container_name: lamp-web
        volumes: 
            - web-data:/var/lib/apache2/
            - web-uploads:/var/www/html/uploads/
        ports: 
            - 8085:80
        depends_on: 
            - mysql
    
    mysql:
        image: rahulraju/simple-php-app:mysql
        container_name: lamp-mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        volumes: 
            - ./mysql-data:/var/lib/mysql/
volumes: 
    web-data:
    web-uploads:
